// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.Datos;

#nullable disable

namespace SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.Migrations
{
    [DbContext(typeof(SigrecDbContext))]
    [Migration("20260828175525_AgregarCorreoCliente")]
    partial class AgregarCorreoCliente
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.ConsultaIA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pregunta")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Respuesta")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Pregunta");

                    b.ToTable("ConsultasIA");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapacidadBTU")
                        .HasColumnType("int");

                    b.Property<int>("ClienteId")
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TipoEquipo")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("Equipos");

                    b.HasDiscriminator<string>("TipoEquipo").HasValue("Equipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Mantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Costo")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DuracionHoras")
                        .HasColumnType("int");

                    b.Property<int>("EquipoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TecnicoId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMantenimiento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("EquipoId");

                    b.HasIndex("TecnicoId");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Repuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Precio")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("TipoRepuesto")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Tecnico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Experiencia")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.ToTable("Tecnicos");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.AireAcondicionado", b =>
                {
                    b.HasBaseType("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo");

                    b.Property<string>("TipoFiltro")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasDiscriminator().HasValue("AireAcondicionado");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.CamaraFrigorifica", b =>
                {
                    b.HasBaseType("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo");

                    b.Property<double>("TemperaturaMinima")
                        .HasColumnType("float");

                    b.HasDiscriminator().HasValue("CamaraFrigorifica");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Refrigerador", b =>
                {
                    b.HasBaseType("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo");

                    b.Property<int>("NumeroPuertas")
                        .HasColumnType("int");

                    b.HasDiscriminator().HasValue("Refrigerador");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo", b =>
                {
                    b.HasOne("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Cliente", "Cliente")
                        .WithMany("Equipos")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cliente");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Mantenimiento", b =>
                {
                    b.HasOne("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo", "Equipo")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("EquipoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Tecnico", "Tecnico")
                        .WithMany("Mantenimientos")
                        .HasForeignKey("TecnicoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Equipo");

                    b.Navigation("Tecnico");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Cliente", b =>
                {
                    b.Navigation("Equipos");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Equipo", b =>
                {
                    b.Navigation("Mantenimientos");
                });

            modelBuilder.Entity("SIGREC__Sistema_de_Gestión_de_Refrigeración_y_Climatización__.models.Tecnico", b =>
                {
                    b.Navigation("Mantenimientos");
                });
#pragma warning restore 612, 618
        }
    }
}
